### ISSUE TITLE
getTorrent performance

### ISSUE THREAD

**Issue by rflaperuta** [rafipiccolo/rtorrent-scgi#1]
Hi!

I Made a new code for getTorrent instead of calling getAll and filtering afterwards. (My issue is running this remotely).

There are several calls inside not optimized in my version.

It would be nice if someone could take a look at it.

``` javascript
Rtorrent.prototype.getTorrent = function(hash, callback) {
    var self = this;

    var array = [];

    var resTorrent;

    // For a Single Torrent
    for (i in fields.torrents)
        array.push({
            'methodName': fields.torrents[i],
            'params': [hash],
        });

    self.getXmlrpc('system.multicall', [array], function (err, data) {
        if (err) return callback(err);

        resTorrent = array2hash(data, Object.keys(fields.torrents));

        resTorrent['state'] = '';
        if (resTorrent['active'] == 1)
            resTorrent['state'] += 'active ';
        if (resTorrent['open'] == 1)
            resTorrent['state'] += 'open ';
        if (resTorrent['complete'] == 1)
            resTorrent['state'] += 'complete ';
        if (resTorrent['hashing'] == 1)
            resTorrent['state'] += 'hashing ';
        if (resTorrent['hashed'] == 1)
            resTorrent['state'] += 'hashed ';
        if (resTorrent['down_total'] < resTorrent['completed'])
            resTorrent['down_total'] = resTorrent['completed'];
        resTorrent['ratio'] = resTorrent['up_total']/resTorrent['down_total'];

        self.getTorrentFiles(hash, function (err, data) {
            if (err) return callback(err);

            resTorrent['files'] = data;

            self.getTorrentPeers(hash, function (err, data) {
                if (err) return callback(err);

                resTorrent['peers'] = data;

                self.getTorrentTrackers(hash, function (err, data) {
                    if (err) return callback(err);

                    resTorrent['trackers'] = data;

                    callback(err, resTorrent)
                });

            });

        });

    });
}
```

**Comment by rafipiccolo** [comment]
hello,

From my experience with rtorrent it seems that the connection itself is the slow point. not the data itself.

Here you have 4 remote calls. So a possible optimisation would be to paralellize all calls (system.multicall, getTorrentFiles, getTorrentPeers, getTorrentTrackers) instead of calling them 1 after the other. you can use async for this.

but i'm not sure the perf will be really better if you try to get many torrents at the same time.

what are you trying to do ?

**Comment by rflaperuta** [comment]
I was trying to get only one torrent information, without the getTorrents loop inside getTorrent.

I made another code, and added the async dependency as you sugested, it seems to be performing better.

Also I have done some other changes to the module, would it be possible to submit them to evaluation? If yes, how could I do that?

Thanks for the tips.

**Comment by rafipiccolo** [comment]
You can do a pull request.
I never tested it but it's the way it works with github.
it means you fork the project. then commit your work. then make a pull request then i see it and integrate it.
